# Generated by Django 5.0.3 on 2024-03-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiants',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('prenom', models.CharField(blank=True, db_column='Prenom', max_length=50, null=True)),
                ('nom', models.CharField(blank=True, db_column='Nom', max_length=50, null=True)),
                ('pays', models.CharField(blank=True, db_column='Pays', max_length=50, null=True)),
                ('adresse', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'etudiants',
                'managed': False,
            },
        ),
    ]
